<?php
G::LoadClass("plugin");

class redirecLoginPlugin extends PMPlugin
{
  
  
  public function redirecLoginPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "redirecLogin Plugin";
    $this->sDescription  = "Autogenerated plugin for class redirecLogin";
    $this->sPluginFolder = "redirecLogin";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    
    
    
    return $res;
  }

  public function setup()
  {
    $this->registerMenu("processmaker", "menuredirecLogin.php");
    $this->registerMenu("cases", "menuCasesredirecLogin.php");
    $this->redirectLogin("PROCESSMAKER_ADMIN","redirecLogin/redirecLoginApplication");
    
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("redirecLogin", __FILE__);
